import { CollegeEvent, Registration, User } from "./types";

export const mockUsers: User[] = [
  { id: "1", name: "Admin User", email: "admin@college.edu", role: "admin" },
  { id: "2", name: "Arjun Mehta", email: "arjun@college.edu", role: "student" },
  { id: "3", name: "Priya Sharma", email: "priya@college.edu", role: "student" },
];

export const mockEvents: CollegeEvent[] = [
  {
    id: "e1",
    title: "TechFest 2026",
    description: "Annual technology festival featuring hackathons, coding competitions, and tech talks from industry leaders. Join us for 48 hours of innovation and creativity.",
    date: "2026-04-15",
    time: "09:00",
    venue: "Main Auditorium",
    category: "Technical",
    posterUrl: "",
    totalSeats: 200,
    registeredCount: 156,
    createdBy: "1",
  },
  {
    id: "e2",
    title: "Spring Cultural Night",
    description: "A vibrant evening of music, dance, and drama performances by students. Celebrate the diversity of our campus community.",
    date: "2026-04-20",
    time: "18:00",
    venue: "Open Air Theatre",
    category: "Cultural",
    posterUrl: "",
    totalSeats: 500,
    registeredCount: 312,
    createdBy: "1",
  },
  {
    id: "e3",
    title: "AI & Machine Learning Workshop",
    description: "Hands-on workshop covering the latest in AI and ML. Bring your laptop and learn to build neural networks from scratch.",
    date: "2026-04-25",
    time: "10:00",
    venue: "Computer Lab 3",
    category: "Workshop",
    posterUrl: "",
    totalSeats: 40,
    registeredCount: 38,
    createdBy: "1",
  },
  {
    id: "e4",
    title: "Inter-College Cricket Tournament",
    description: "Annual cricket tournament with teams from 12 colleges competing for the Chancellor's Trophy.",
    date: "2026-05-01",
    time: "07:00",
    venue: "Sports Ground",
    category: "Sports",
    posterUrl: "",
    totalSeats: 120,
    registeredCount: 89,
    createdBy: "1",
  },
  {
    id: "e5",
    title: "Career Guidance Seminar",
    description: "Industry professionals share insights on career paths in technology, management, and research. Networking session included.",
    date: "2026-05-10",
    time: "14:00",
    venue: "Seminar Hall B",
    category: "Seminar",
    posterUrl: "",
    totalSeats: 150,
    registeredCount: 67,
    createdBy: "1",
  },
  {
    id: "e6",
    title: "Freshers' Welcome Party",
    description: "Welcome the new batch with music, games, and fun activities. A great way to make new friends and kickstart your college journey.",
    date: "2026-05-15",
    time: "17:00",
    venue: "Student Center",
    category: "Social",
    posterUrl: "",
    totalSeats: 300,
    registeredCount: 142,
    createdBy: "1",
  },
];

export const mockRegistrations: Registration[] = [
  { id: "r1", eventId: "e1", studentId: "2", studentName: "Arjun Mehta", studentEmail: "arjun@college.edu", status: "approved", registeredAt: "2026-03-20T10:00:00Z" },
  { id: "r2", eventId: "e1", studentId: "3", studentName: "Priya Sharma", studentEmail: "priya@college.edu", status: "pending", registeredAt: "2026-03-21T14:30:00Z" },
  { id: "r3", eventId: "e2", studentId: "2", studentName: "Arjun Mehta", studentEmail: "arjun@college.edu", status: "approved", registeredAt: "2026-03-19T09:15:00Z" },
  { id: "r4", eventId: "e3", studentId: "3", studentName: "Priya Sharma", studentEmail: "priya@college.edu", status: "rejected", registeredAt: "2026-03-22T16:45:00Z" },
];
